Feat: Implement GRPC connection to Triton Inference serving crd
IBM/OpenShift-AI-Toolkit-Operator pull request #1
Opened 2024-12-26 13:30 UTC by dilipgb

Hi, this PR implements the feature to allow GRPC connection from triton inference service.

Motivation: The GRPC connections in Openshift is allowed only over secure channel due to use of TLS extension called Application-Level Protocol Negotiation (ALPN) by HAProxy, to negotiate the use of HTTP/2 between HAProxy itself and the back-end application service. So there is a need handle grpc traffic in encrypted mode.

Implementation: 

- Code checks for secret name passed for tls. If secretname is passed it will try to create the pvc and mount tls.crt and tls.key files in the prespecified path.
- If secret does not exist, the server is started without tls.
- The route is configured in tls passthrough mode only for grpc. There is a condition to check for route name contains grpc and if its grpc connections it tries to create the route in passthrough mode.

2024-12-26 14:18 UTC, ShivangGoswami reviewed
needs improvement. reassigned for same

2024-12-26 14:18 UTC, ShivangGoswami commented on api/v1alpha1/tritoninterfaceserver_types.go
> +	TlsSecretName string `json:"tlsSecretName,omitempty"` // The TLS Secret Name (optional)
comments should be above the variable definition. Including both inline and comment above makes the code unclean and readability is reduced

2024-12-26 14:18 UTC, ShivangGoswami commented on api/v1alpha1/tritoninterfaceserver_types.go
> +	// TLSSpec includes the TLS Secret Name (optional)
optional/required is defined by kubebuilder labels and docs processes it. So no need to mention again in the description

2024-12-26 14:18 UTC, ShivangGoswami commented on bundle/manifests/openshift-ai-toolkit.clusterserviceversion.yaml
> +                image: quay.io/dbhagava/openshift-ai-toolkit-operator-controller:latest
this is not required. Changes to push to personal quay account is highly discouraged

2024-12-26 14:18 UTC, ShivangGoswami commented on config/manager/kustomization.yaml
> +  newName: quay.io/dbhagava/openshift-ai-toolkit-operator-controller
this is not required. Changes to push to personal quay account is highly discouraged

2024-12-26 14:18 UTC, ShivangGoswami commented on internal/controller/deployment.go
> +					Volumes: func() []corev1.Volume {
This definition of function here is problematic. please refrain from using closures and include all if conditions in the main function itself. There is cost to define functions and we can't do it for 2 if conditions

2024-12-26 14:18 UTC, ShivangGoswami commented on internal/controller/deployment.go
> +							Args: func() []string {
same comment as above

2024-12-26 14:18 UTC, ShivangGoswami commented on internal/controller/deployment.go
> +							VolumeMounts: func() []corev1.VolumeMount {
same comment as above

2024-12-26 14:21 UTC, ShivangGoswami commented
The Documentation updation for grpc based calls are missing here. PR should be self contained with all changes linked to all scopes: dev + docs. if docs are not updated proper reasoning should be provided for the same

2024-12-26 14:29 UTC, ShivangGoswami commented
The Attribute addition here is not proper because

- TLSSpec->TLSSecretName 

This definition in not providing complete insights to the functionality and user will be confused whether this is applicable to grace,http or metrics endpoints.

Since it is specific to grpc endpoint something like this

- GRPCConfig->TLSSpec->TLSSecretName

is a good design approach.

Since the TLSSecretName is the only functionality provided here as of now. There are more approaches like providing key within the spec file or generate one if user doesn't provide(Can't comment much here since flow and architecture were not defined for these changes)
Whatever functionality is being provided here utilities for the same should be added here.

2024-12-27 09:56 UTC, dilipgb commented
@ShivangGoswami plese review. Comments are incorporated and docs are updated.

2025-01-03 05:34 UTC, ShivangGoswami requested changes
code changes seems good now.Documentation needs to be improved.

2025-01-03 05:34 UTC, ShivangGoswami commented on README.md
> +
in the using the endpoint section, gRPC calls should be updated for the user to try as a DIY effort

2025-01-03 05:34 UTC, ShivangGoswami commented on README.md
> +oc create secret tls tls-secret --cert=tls/tls.crt --key=tls/tls.key
mention commands used to generate key and certs. This documentation is intended for everyone(excluding people with less technical awareness) should minor details should be included here

2025-01-03 05:35 UTC, ShivangGoswami commented
@dilipgb good work with the code changes.please rectify docs changes as well.

2025-01-03 05:36 UTC, ShivangGoswami commented
This can be merged after peer validation is done i.e this code needs to be tried on a running openshift instance

2025-01-06 06:52 UTC, dilipgb commented on README.md
> +
Added the sample request along with the output.

2025-01-06 06:57 UTC, dilipgb commented
@ShivangGoswami this changes is already been verified by AI team. We can discuss if you are looking anything specific. Please find the attached screenshots for your reference.

sample deployment and pod:
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/4028631b-bc0d-40d6-bbf6-b652ef268abd" />
Sample service and Route:
<img width="806" alt="image" src="https://github.com/user-attachments/assets/14f5a840-a651-4263-af2d-7152f5d4a78c" />
Sample GRPC response:
<img width="724" alt="image" src="https://github.com/user-attachments/assets/ec3f75d5-95c1-4b9e-ad31-2ce91e7322a2" />

2025-01-06 12:55 UTC, modassarrana89 commented on README.md
> +  [root@api.ia-4-8-0-online-upgrade.cp.fyre.ibm.com grpc_proto_files]# python gRPC_Python_Inference_test.py  -u grpc-route-triton-server-71885c45-triton-pvc-test-grpc.apps.ia-4-8-0-online-upgrade.cp.
@dilipgb I am not able to locate gRPC_Python_Inference_test.py file . If not uploaded , please upload so that user can use that to create sample grpc request . Do Please explain all the args that you have passed for the python scripts .

2025-01-06 18:47 UTC, ShivangGoswami commented
merged via #4

2025-01-10 07:00 UTC, closed without merging